language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements-test.txt
script:
  - python -m pytest --cov=statbus